# Generated by Django 5.2.12 on 2026-03-13 23:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_user_id_to_uuid(apps, schema_editor):
    """Convert User.id from bigint to UUID. PostgreSQL cannot cast directly."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT tc.table_name, tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.constraint_column_usage ccu
                ON tc.constraint_name = ccu.constraint_name
            WHERE tc.constraint_type = 'FOREIGN KEY'
            AND ccu.table_name = 'users' AND ccu.column_name = 'id'
            """
        )
        fks_to_drop = cursor.fetchall()

        for table_name, constraint_name in fks_to_drop:
            cursor.execute(f'ALTER TABLE "{table_name}" DROP CONSTRAINT IF EXISTS "{constraint_name}"')

        cursor.execute('ALTER TABLE "users" ADD COLUMN "id_uuid" uuid NULL;')
        cursor.execute('SELECT "id" FROM "users"')
        rows = cursor.fetchall()
        id_map = {old_id: str(uuid.uuid5(uuid.NAMESPACE_DNS, str(old_id))) for (old_id,) in rows}
        for old_id, new_uuid in id_map.items():
            cursor.execute(
                'UPDATE "users" SET "id_uuid" = %s::uuid WHERE "id" = %s',
                [new_uuid, old_id],
            )

        user_fk_tables = [
            "users_groups", "users_user_permissions", "accounts_user_groups",
            "accounts_user_user_permissions", "django_admin_log", "projects_project",
            "sessions_focus_session", "sessions_timer_state", "chat_sessions_focus_session",
            "chat_sessions_timer_state",
        ]
        for table in user_fk_tables:
            cursor.execute(
                "SELECT 1 FROM information_schema.tables WHERE table_name = %s",
                [table],
            )
            if cursor.fetchone():
                cursor.execute(
                    "SELECT 1 FROM information_schema.columns WHERE table_name = %s AND column_name = 'user_id'",
                    [table],
                )
                if cursor.fetchone():
                    cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN "user_id_uuid" uuid NULL;')
                    for old_id, new_uuid in id_map.items():
                        cursor.execute(
                            f'UPDATE "{table}" SET "user_id_uuid" = %s::uuid WHERE "user_id" = %s',
                            [new_uuid, old_id],
                        )
                    cursor.execute(f'ALTER TABLE "{table}" DROP COLUMN "user_id"')
                    cursor.execute(f'ALTER TABLE "{table}" RENAME COLUMN "user_id_uuid" TO "user_id"')

        cursor.execute('ALTER TABLE "users" DROP CONSTRAINT "users_pkey"')
        cursor.execute('ALTER TABLE "users" DROP COLUMN "id"')
        cursor.execute('ALTER TABLE "users" RENAME COLUMN "id_uuid" TO "id"')
        cursor.execute(
            'ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id")'
        )

        for table_name, _ in fks_to_drop:
            cursor.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_name = %s AND column_name = 'user_id'",
                [table_name],
            )
            if cursor.fetchone():
                fk_name = f"{table_name}_user_id_fkey"
                cursor.execute(
                    f'ALTER TABLE "{table_name}" ADD CONSTRAINT "{fk_name}" '
                    'FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED'
                )


def reverse_migrate_user_id(apps, schema_editor):
    raise NotImplementedError("Cannot reverse UUID to bigint migration")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat_sessions', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_goal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
        migrations.AddField(
            model_name='user',
            name='daily_goal_minutes',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(migrate_user_id_to_uuid, reverse_migrate_user_id),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='user',
            name='supabase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
        migrations.CreateModel(
            name='XpEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('session_complete', 'Session complete'), ('task_done', 'Task done'), ('streak_bonus', 'Streak bonus'), ('level_up', 'Level up'), ('brain_dump', 'Brain dump'), ('daily_goal', 'Daily goal met')], max_length=50)),
                ('xp_amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='chat_sessions.focussession')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_xp_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreakDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('focus_minutes', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('sessions_completed', models.IntegerField(default=0)),
                ('goal_met', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_streak_day',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
