# Generated by Django 5.2.12 on 2026-03-13 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("standup", "Standup"),
                            ("breakdown", "Breakdown"),
                            ("rubber_duck", "Rubber Duck"),
                            ("context_summary", "Context Summary"),
                            ("brain_dump", "Brain Dump"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "model",
                    models.CharField(default="llama-3.3-70b-versatile", max_length=100),
                ),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_messages",
                        to="projects.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_messages",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_assistant_ai_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Standup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("standup_date", models.DateField()),
                ("raw_summary", models.TextField()),
                ("highlights", models.JSONField(default=list)),
                ("blockers", models.JSONField(default=list)),
                ("suggestions", models.JSONField(default=list)),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_assistant_standup",
                "ordering": ["-standup_date"],
                "unique_together": {("user", "standup_date")},
            },
        ),
    ]
