# Generated by Django 5.2.12 on 2026-03-13 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#185FA5', max_length=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('archived', 'Archived')], default='active', max_length=20)),
                ('github_repo', models.CharField(blank=True, max_length=200)),
                ('github_repo_id', models.BigIntegerField(blank=True, null=True)),
                ('github_default_branch', models.CharField(default='main', max_length=100)),
                ('last_context', models.TextField(blank=True)),
                ('health_score', models.IntegerField(default=100)),
                ('total_focus_minutes', models.IntegerField(default=0)),
                ('last_session_at', models.DateTimeField(blank=True, null=True)),
                ('last_commit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_project',
                'ordering': ['-last_session_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_score', models.IntegerField()),
                ('commits_this_week', models.IntegerField(default=0)),
                ('open_prs', models.IntegerField(default=0)),
                ('avg_pr_age_days', models.IntegerField(default=0)),
                ('focus_minutes_this_week', models.IntegerField(default=0)),
                ('tasks_completed_this_week', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('signals', models.JSONField(default=dict)),
                ('snapped_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='projects.project')),
            ],
            options={
                'db_table': 'projects_health_snapshot',
                'ordering': ['-snapped_at'],
            },
        ),
        migrations.CreateModel(
            name='GithubPR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('pr_opened_at', models.DateTimeField(blank=True, null=True)),
                ('pr_merged_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='projects.project')),
            ],
            options={
                'db_table': 'projects_github_pr',
                'ordering': ['-pr_opened_at'],
                'unique_together': {('project', 'pr_number')},
            },
        ),
        migrations.CreateModel(
            name='GithubCommit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('author_email', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='projects.project')),
            ],
            options={
                'db_table': 'projects_github_commit',
                'ordering': ['-committed_at'],
                'unique_together': {('project', 'sha')},
            },
        ),
    ]
