# Generated by Django 5.2.12 on 2026-04-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goals',
            field=models.TextField(blank=True),
        ),
    ]
